Repository samvera/active_fedora, pull requests merged in 2019-05, with the labels that each got.

#1387 Updates the CircleCI configuration to test against Rails release 5.1.7, along with Ruby releases 2.6.3, 2.5.5, and 2.4.6
  .circleci/config.yml
Labels: in progress

#1294 Rename solr/config directory to solr/conf
  .circleci/config.yml
  .solr_wrapper
  lib/active_fedora/rake_support.rb
  lib/generators/active_fedora/config/solr/templates/.solr_wrapper.yml
  lib/generators/active_fedora/config/solr/templates/solr/conf/_rest_managed.json
  lib/generators/active_fedora/config/solr/templates/solr/conf/admin-extra.html
  lib/generators/active_fedora/config/solr/templates/solr/conf/elevate.xml
  lib/generators/active_fedora/config/solr/templates/solr/conf/mapping-ISOLatin1Accent.txt
  lib/generators/active_fedora/config/solr/templates/solr/conf/protwords.txt
  lib/generators/active_fedora/config/solr/templates/solr/conf/schema.xml
  lib/generators/active_fedora/config/solr/templates/solr/conf/scripts.conf
  lib/generators/active_fedora/config/solr/templates/solr/conf/solrconfig.xml
  lib/generators/active_fedora/config/solr/templates/solr/conf/spellings.txt
  lib/generators/active_fedora/config/solr/templates/solr/conf/stopwords.txt
  lib/generators/active_fedora/config/solr/templates/solr/conf/stopwords_en.txt
  lib/generators/active_fedora/config/solr/templates/solr/conf/synonyms.txt
  lib/generators/active_fedora/config/solr/templates/solr/conf/xslt/example.xsl
  lib/generators/active_fedora/config/solr/templates/solr/conf/xslt/example_atom.xsl
  lib/generators/active_fedora/config/solr/templates/solr/conf/xslt/example_rss.xsl
  lib/generators/active_fedora/config/solr/templates/solr/conf/xslt/luke.xsl
  lib/generators/active_fedora/config/solr/templates/solr_wrapper_test.yml
Labels: maintenance review, review

#1384 Removes the dependency for solrizer
  active-fedora.gemspec
  lib/active_fedora.rb
  lib/active_fedora/indexing.rb
  lib/active_fedora/indexing/descriptor.rb
  lib/active_fedora/indexing/field_mapper.rb
  lib/active_fedora/indexing/suffix.rb
Labels: review
